# Generated by Django 4.2.6 on 2023-11-05 16:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=150, verbose_name='имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='фамилия')),
                ('comment', models.TextField(max_length=300, verbose_name='комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_from', models.DateTimeField(default=datetime.datetime(2023, 11, 5, 19, 27, 33, 469594), verbose_name='время рассылки с')),
                ('datetime_to', models.DateTimeField(default=datetime.datetime(2023, 11, 5, 23, 27, 33, 469594), verbose_name='время рассылки до')),
                ('frequency', models.CharField(max_length=150, verbose_name='периодичность')),
                ('status', models.BooleanField(default=False, verbose_name='статус рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=150, verbose_name='тема письма')),
                ('text', models.TextField(verbose_name='тело письма')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailing_service.client', to_field='email', verbose_name='клиент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='отправитель')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='время последней попытки')),
                ('status', models.BooleanField(default=False, verbose_name='статус попытки')),
                ('answer_mail_server', models.CharField(default='', max_length=150, verbose_name='ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailing_service.mailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'лог рассылки',
                'verbose_name_plural': 'логи рассылки',
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailing_service.mailingmessage', verbose_name='сообщение'),
        ),
    ]
