# Generated by Django 4.2.6 on 2023-11-06 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0005_alter_mailing_datetime_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailingmessage',
            old_name='client',
            new_name='clients',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='datetime_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 23, 26, 10, 69316), verbose_name='время рассылки с'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='datetime_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 23, 26, 10, 69316), verbose_name='время рассылки до'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='frequency',
            field=models.IntegerField(verbose_name='периодичность в днях'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.BooleanField(default=True, verbose_name='статус рассылки'),
        ),
    ]
