# Generated by Django 4.2.6 on 2023-11-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogmaterial_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmaterial',
            old_name='imd',
            new_name='img',
        ),
    ]
